### ISSUE TITLE
To-Do for API and docs

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/PointNeighbors.jl#28]
- [ ] #27 
- [ ] Write README.
- [ ] Rename `for_particle_neighbor` to `foreach_point_neighbor`.
- [ ] Replace `particle` by `point` everywhere.
- [ ] Add benchmark plot to README.
- [ ] Write comparison table for all implementations.
